# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version tools you might need
build:
  os: ubuntu-latest
  tools:
    pwsh: "7.3.7"

mkdocs:
  configuration: docs/mkdocs.yml