site_name: ibPS
theme:
  name: material
  #logo: images/v.svg
  features:
    - navigation.expand
  palette:
    primary: indigo
repo_url: https://github.com/TehMuffinMoo/ibPS
repo_name: ibPS
edit_uri: ""
docs_dir: .
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - Home: index.md
  - Functions:
    - BloxOne:
    - NIOS:
      - Copy-NIOSSubzoneToBloxOne: Functions/NIOS/Copy-NIOSSubzoneToBloxOne.md
      - Get-NIOSAuthoritativeZone: Functions/NIOS/Get-NIOSAuthoritativeZone.md
      - Get-NIOSConfiguration: Functions/NIOS/Get-NIOSConfiguration.md
      - Get-NIOSCredentials: Functions/NIOS/Get-NIOSCredentials.md
      - Get-NIOSDelegatedZone: Functions/NIOS/Get-NIOSDelegatedZone.md
      - Get-NIOSForwardZone: Functions/NIOS/Get-NIOSForwardZone.md
      - New-NIOSDelegatedZone: Functions/NIOS/New-NIOSDelegatedZone.md
      - Set-NIOSConfiguration: Functions/NIOS/Set-NIOSConfiguration.md
      - Store-NIOSCredentials: Functions/NIOS/Store-NIOSCredentials.md
      - Query-NIOS: Functions/NIOS/Copy-NIOSSubzoneToBloxOne.md