name: Publish PowerShell Module (Dev)

on:
  push:
    branches: [dev]

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        shell: pwsh
        run: |
          cd ibPS
          Publish-Module -Name "ibPS-Dev" -NuGetApiKey $env:NUGET_KEY -SkipAutomaticTags -Verbose