name: Increment Build

on:
  push:
    branches:
      - dev

jobs:
  Increment-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Update Build Version
        shell: pwsh
        run : |
          $Build = Get-Content Modules/ibPS/Functions/Misc/build.json | ConvertFrom-Json
          $BuildVer = $Build.build -split '\.'
          $BuildVer[3] = [Int]$BuildVer[3]+1
          $Build.build = $BuildVer -join '.'
          $Build.sha = $ENV:GITHUB_SHA
          $ENV:BuildVersion = $Build.build
          Set-Content -Path Modules/ibPS/Functions/Misc/build.json -Value $($Build | ConvertTo-Json)
          cat Modules/ibPS/Functions/Misc/build.json

      - name: Update Repository
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.password ${{ secrets.GIT_ACTIONS }}
          git config --global user.email 'mat.cox@tmmn.uk'
          git add .
          git status
          if ! git diff-index --quiet HEAD; then
            git commit -m "Updated Build Version (${{ env.BuildVersion }})"
            git push
          else
            echo "Build Version Not Changed."
          fi
