name: Publish PowerShell Module (Gallery Only)

on: workflow_dispatch

jobs:
  PSGallery-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and publish
        id: build
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        shell: pwsh
        run: |
          Copy-Item 'Modules/ibPS' '/home/runner/.local/share/powershell/Modules/' -Recurse
          $Manifest = Test-ModuleManifest 'Modules/ibPS/ibPS.psd1'
          if ($($Manifest.Version) -gt $(Find-Module ibPS).Version) {
            Write-Host "Publishing v$($Manifest.Version.ToString()).."
            Publish-Module -Name "ibPS" -NuGetApiKey $env:NUGET_KEY -SkipAutomaticTags -Verbose
            Write-Output "ReleaseUpdated=true" | Out-File -FilePath $ENV:GITHUB_ENV -Encoding utf8 -Append
          } else {
            Write-Host "Version number is the same, skipping publishing.."
            Write-Output "ReleaseUpdated=false" | Out-File -FilePath $ENV:GITHUB_ENV -Encoding utf8 -Append
          }
          $Version = "v$($Manifest.Version.ToString())"
          Write-Output "Version=$($Version)" | Out-File -FilePath $ENV:GITHUB_ENV -Encoding utf8 -Append
          Write-Output "ReleaseNotes=$($Manifest.ReleaseNotes)" | Out-File -FilePath $ENV:GITHUB_ENV -Encoding utf8 -Append
      - name: Create Release
        if: ${{ env.ReleaseUpdated == 'true' }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_ACTIONS }}
        with:
          tag_name: ${{ env.Version }}
          release_name: Release ${{ env.Version }}
          body: ${{ env.ReleaseNotes }}
          draft: false
          prerelease: false
