name: Publish PowerShell Module

on:
  push:
    branches: [main]

jobs:
  PSGallery-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and publish
        id: build
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        shell: pwsh
        run: |
          Copy-Item 'Modules/ibPS' '/home/runner/.local/share/powershell/Modules/' -Recurse
          $Manifest = Test-ModuleManifest 'Modules/ibPS/ibPS.psd1'
          if ($($Manifest.Version) -gt $(Find-Module ibPS).Version) {
            Write-Host "Publishing v$($Manifest.Version.ToString()).."
            Publish-Module -Name "ibPS" -NuGetApiKey $env:NUGET_KEY -SkipAutomaticTags -Verbose
          } else {
            Write-Host "Version number is the same, skipping publishing.."
          }
          $Version = "v$($Manifest.Version.ToString())"
          Write-Output "Version=$($Version)" | Out-File -FilePath $ENV:GITHUB_ENV -Encoding utf8 -Append
          Write-Output "ReleaseNotes=$($Manifest.ReleaseNotes)" | Out-File -FilePath $ENV:GITHUB_ENV -Encoding utf8 -Append
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_ACTIONS }}
        with:
          tag_name: ${{ steps.build.outputs.version }}
          release_name: Release ${{ steps.build.outputs.Version }}
          body: ${{ steps.build.outputs.ReleaseNotes }}
          draft: true
          prerelease: false